/** A single image (thumbnail, avatar, banner) as returned by YouTube. */
export interface Thumbnail {
  url: string;
  width: number;
  height: number;
}

/** Minimal channel reference embedded in videos, playlists and comments. */
export interface ChannelRef {
  id: string | null;
  name: string;
  url: string | null;
  thumbnails: Thumbnail[];
  verified: boolean;
}

/** A video as it appears in a list (search results, related, playlist, channel). */
export interface VideoCompact {
  type: 'video';
  id: string;
  title: string;
  url: string;
  thumbnails: Thumbnail[];
  /** Duration in seconds; null for live streams and upcoming premieres. */
  durationSeconds: number | null;
  durationText: string | null;
  viewCount: number | null;
  viewCountText: string | null;
  /** Relative upload text as shown by YouTube, e.g. "3 days ago". */
  publishedText: string | null;
  channel: ChannelRef | null;
  description: string | null;
  isLive: boolean;
  isUpcoming: boolean;
}

/** Full metadata for a single video. */
export interface VideoDetails extends Omit<VideoCompact, 'publishedText' | 'description'> {
  description: string;
  /** ISO-8601 date, e.g. "2024-05-01"; null when YouTube does not expose it. */
  publishDate: string | null;
  uploadDate: string | null;
  keywords: string[];
  category: string | null;
  likeCount: number | null;
  /** Live viewer count while a stream is running. */
  liveViewers: number | null;
  isFamilySafe: boolean | null;
  isPrivate: boolean;
  isUnlisted: boolean;
  allowRatings: boolean;
  availableCaptions: CaptionTrack[];
  chapters: Chapter[];
  /** Present only when `getStreams` / `withStreams` was used. */
  streams?: StreamFormat[];
}

/** A chapter marker parsed out of the video description / macro markers. */
export interface Chapter {
  title: string;
  startSeconds: number;
  thumbnails: Thumbnail[];
}

/** A downloadable / playable stream variant. */
export interface StreamFormat {
  itag: number;
  url: string | null;
  mimeType: string;
  /** "video", "audio" or "video+audio". */
  kind: 'video' | 'audio' | 'video+audio';
  codecs: string;
  bitrate: number | null;
  width: number | null;
  height: number | null;
  fps: number | null;
  /** e.g. "1080p", "medium". */
  qualityLabel: string | null;
  audioQuality: string | null;
  audioSampleRate: number | null;
  audioChannels: number | null;
  contentLength: number | null;
  durationMs: number | null;
  /** True when the URL needs signature deciphering that we could not perform. */
  requiresCipher: boolean;
  /** DASH/HLS segmented formats are not plain progressive downloads. */
  isAdaptive: boolean;
}

/** Everything needed to play a video, including manifest URLs. */
export interface StreamBundle {
  videoId: string;
  formats: StreamFormat[];
  /** Progressive formats carry both video and audio in one file. */
  progressive: StreamFormat[];
  adaptive: StreamFormat[];
  hlsManifestUrl: string | null;
  dashManifestUrl: string | null;
  /** Seconds until the stream URLs stop working. */
  expiresInSeconds: number | null;
}

/** A caption/subtitle track available for a video. */
export interface CaptionTrack {
  languageCode: string;
  languageName: string;
  url: string;
  /** True for machine generated (ASR) captions. */
  isAutoGenerated: boolean;
  isTranslatable: boolean;
}

/** One cue of a fetched transcript. */
export interface TranscriptSegment {
  text: string;
  startSeconds: number;
  durationSeconds: number;
}

/** A channel as it appears in a list. */
export interface ChannelCompact {
  type: 'channel';
  id: string;
  name: string;
  url: string;
  handle: string | null;
  thumbnails: Thumbnail[];
  subscriberCount: number | null;
  subscriberCountText: string | null;
  videoCountText: string | null;
  description: string | null;
  verified: boolean;
}

/** Full channel metadata. */
export interface ChannelDetails extends ChannelCompact {
  banners: Thumbnail[];
  keywords: string[];
  /** Links shown on the channel's about page. */
  links: { title: string; url: string }[];
  country: string | null;
  joinedDate: string | null;
  viewCount: number | null;
  isFamilySafe: boolean | null;
  tabs: string[];
  /**
   * True when the channel offers a paid membership ("Join" button present).
   *
   * Only the existence is visible to anonymous callers — YouTube requires a
   * sign-in before it will name the tiers or their prices. The tier a given
   * video requires is reported by `MembersOnlyError.requiredTier` instead.
   */
  hasMemberships: boolean;
}

/** A playlist as it appears in a list. */
export interface PlaylistCompact {
  type: 'playlist';
  id: string;
  title: string;
  url: string;
  thumbnails: Thumbnail[];
  videoCount: number | null;
  channel: ChannelRef | null;
}

/** Full playlist metadata with its (first page of) items. */
export interface PlaylistDetails extends PlaylistCompact {
  description: string | null;
  viewCount: number | null;
  lastUpdatedText: string | null;
  videos: VideoCompact[];
}

/** A top-level comment or a reply. */
export interface Comment {
  id: string;
  text: string;
  author: ChannelRef;
  likeCount: number | null;
  publishedText: string | null;
  replyCount: number | null;
  isPinned: boolean;
  isHearted: boolean;
  isAuthorChannelOwner: boolean;
  /** Continuation token to fetch this comment's replies, if any. */
  repliesToken: string | null;
}

/** Anything a search can return. */
export type SearchResult = VideoCompact | ChannelCompact | PlaylistCompact;

/** Search filter options. */
export interface SearchOptions {
  /** Restrict to one kind of result. */
  type?: 'video' | 'channel' | 'playlist' | 'movie' | 'all';
  /** Upload recency filter. */
  uploadDate?: 'hour' | 'today' | 'week' | 'month' | 'year';
  duration?: 'short' | 'medium' | 'long';
  sortBy?: 'relevance' | 'date' | 'views' | 'rating';
  features?: ('live' | 'hd' | '4k' | 'subtitles' | 'creativeCommons' | '360' | 'hdr' | 'vr180')[];
  /** Stop after roughly this many results (default 20, paginates as needed). */
  limit?: number;
}

/** A lazily paginated list of results. */
export interface Page<T> {
  items: T[];
  /** Opaque token for the next page, or null when exhausted. */
  continuation: string | null;
}

/** A community (posts tab) entry. */
export interface CommunityPost {
  id: string;
  text: string;
  author: ChannelRef;
  publishedText: string | null;
  likeCountText: string | null;
  replyCountText: string | null;
  /** Images attached to the post, if any. */
  images: Thumbnail[];
  /** A video or playlist shared by the post. */
  attachment: VideoCompact | PlaylistCompact | null;
  /** Poll choices, when the post is a poll. */
  pollChoices: string[];
}

/** One message from a live chat stream. */
export interface LiveChatMessage {
  id: string;
  text: string;
  author: ChannelRef;
  /** Timestamp in microseconds since the epoch. */
  timestampUsec: number;
  /** Set for Super Chat / Super Sticker messages, e.g. "¥500". */
  purchaseAmount: string | null;
  isModerator: boolean;
  isMember: boolean;
  /** True when the message came from the channel owner. */
  isOwner: boolean;
  /**
   * Membership badge text as YouTube renders it, e.g. "メンバー（2 年）"
   * or "Member (2 years)". Null when the author is not a member.
   */
  memberBadge: string | null;
  /** Membership length in months parsed from the badge, when it states one. */
  memberMonths: number | null;
  /** The membership badge image (16px and 32px variants). */
  memberBadgeThumbnails: Thumbnail[];
  /** Emoji and channel stickers used in the message, in order of appearance. */
  emojis: ChatEmoji[];
}

/** A standard emoji or a channel's custom sticker used in a chat message. */
export interface ChatEmoji {
  /** `:shortcut:` form, e.g. ":_しゅごい:" or ":oncoming_fist:". */
  shortcut: string;
  /** YouTube's id: the literal character for standard emoji, else a long id. */
  id: string;
  /** True for a channel's own sticker (usually members-only). */
  isCustom: boolean;
  thumbnails: Thumbnail[];
}
